### ISSUE TITLE
issue reading biotools.json from current version of API bio.tools

### ISSUE THREAD

**Issue by abotzki** [bio-tools/pub2tools#2]
Hi, when using the JSON file from an API call of bio.tools
e.g. https://bio.tools/api/t/?collectionID=%22VIB%22&format=json&page=1 
I encounter parsing errors like the one below.
It seems to be that several properties (e.g. publication type or rorid of persons etc) present in the JSON are not accepted by the parser of pub2tools.

Any feedback is appreciated.

Cheers, Alex

```
$ java -jar target/pub2tools-1.0.0.jar -pass2 output
2020-08-13 22:04:35,817 INFO  This is Pub2Tools 1.0.0 (https://github.com/bio-tools/pub2tools) pub2tools.Pub2Tools main
2020-08-13 22:04:36,242 INFO  Loading IDF from output\tf.idf pub2tools.Pass2 main
2020-08-13 22:04:39,320 INFO  Loading all bio.tools content from output\biotools.json pub2tools.Pass2 main
2020-08-13 22:04:39,822 ERROR Exception! pub2tools.Pub2Tools main
 com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `org.edamontology.edammap.core.input.json.DocumentationType` out of START_ARRAY token
 at [Source: (FileInputStream); line: 134, column: 19] (through reference chain: org.edamontology.edammap.core.input.json.Biotools["list"]->java.util.ArrayList[0]->org.edamontology.edammap.core.input.json.Tool["documentation"]->java.util.ArrayList[0]->org.edamontology.edammap.core.input.json.Link["type"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1216) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:714) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeOther(EnumDeserializer.java:265) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:206) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202) ~[jackson-databind-2.10.2.jar:2.10.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3242) ~[jackson-databind-2.10.2.jar:2.10.2]
        at org.edamontology.edammap.core.input.Json.load(Json.java:49) ~[edammap-core-1.0.0.jar:?]
        at tools.bio.pub2tools.Pass2.run(Pass2.java:1217) ~[pub2tools-1.0.0.jar:?]
        at tools.bio.pub2tools.Pub2Tools.pass2(Pub2Tools.java:261) ~[pub2tools-1.0.0.jar:?]
        at tools.bio.pub2tools.Pub2Tools.run(Pub2Tools.java:473) ~[pub2tools-1.0.0.jar:?]
        at tools.bio.pub2tools.Pub2Tools.main(Pub2Tools.java:613) [pub2tools-1.0.0.jar:?]
```

**Comment by abotzki** [comment]
update: as far as I could figure out the properties below are not found

```
org.edamontology.edammap.core.input.json.Tool["publication"]->java.util.ArrayList[0]->org.edamontology.edammap.core.input.json.Publication["type"])
org.edamontology.edammap.core.input.json.Tool["credit"]->java.util.ArrayList[0]->org.edamontology.edammap.core.input.json.Credit["rorid"]
org.edamontology.edammap.core.input.json.Tool["credit"]->java.util.ArrayList[0]->org.edamontology.edammap.core.input.json.Credit["fundrefid"]
org.edamontology.edammap.core.input.json.Tool["documentation"]->java.util.ArrayList[0]->org.edamontology.edammap.core.input.json.Link["type"])
org.edamontology.edammap.core.input.json.Tool["link"]->java.util.ArrayList[0]->org.edamontology.edammap.core.input.json.Link["type"]```

**Comment by jaanisoe** [comment]
Hello,
Sorry for the late answer and thanks for reporting the issue. The breakage was caused by Pub2Tools not supporting the latest version of biotoolsSchema, that bio.tools migrated to at some point. The latest version of Pub2Tools (1.1.0) should fix the issue: https://github.com/bio-tools/pub2tools/releases/tag/v1.1.0
